"""empty message

Revision ID: f29c303fc6c1
Revises: 3d1d2aafafa6
Create Date: 2022-06-18 15:42:50.198622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c303fc6c1'
down_revision = '3d1d2aafafa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'some')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('some', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
